GH Pages: add QA workflows
rmccue/Requests pull request #528
Opened 2021-09-15 01:07 UTC by jrfnl

This commit adds two workflows:
1. A workflow which tests that the GH Pages site can be generated by Jekyll without errors for pull requests to the `ghpages` branch.
2. A workflow which will crawl the website once a month to look for broken links and will open an issue if any are found.

Notes:
* We may need to do some further trial and error with the config of the broken links action, but getting these workflows in is the first step.
* Both workflows got a safeguard in place to prevent these workflows from running on forks which can't deploy the GH Pages website.

Ref: https://github.com/technote-space/broken-link-checker-action/blob/main/action.yml

2021-09-15 04:17 UTC, jrfnl commented
Note: in the latest version of this PR, I have turned `RECURSIVE` off in the broken link check workflow, but with that turned off, the site doesn't get properly scanned.

However, with it turned on, the scan looks to go into an infinite loop: https://github.com/WordPress/Requests/runs/3605224103?check_suite_focus=true (currently running for 3 hours already)

I also get the impression that the action checks links time and again, even when checked before in the same run.
I've opened an issue about that upstream: https://github.com/technote-space/broken-link-checker-action/issues/131

We may want to remove the broken link workflow from this PR for now until a more stable solution is found.

2021-09-17 10:11 UTC, schlessera requested changes

2021-09-17 10:11 UTC, schlessera commented on .github/workflows/test-ghpages.yml
> +  #### TEST THAT THE GH PAGES SITE GETS BUILD WITHOUT ERRORS ####
```suggestion
  #### TEST THAT THE GH PAGES SITE GETS BUILT WITHOUT ERRORS ####
```

2021-09-17 10:11 UTC, schlessera commented on .github/workflows/test-ghpages.yml
> +          # Use the version as per https://pages.github.com/versions/
```suggestion
          # Use the version as per https://pages.github.com/versions/.
```

2021-09-17 10:12 UTC, schlessera approved these changes

2021-09-17 10:13 UTC, merged

2021-09-17 10:13 UTC, jrfnl commented
Note: removed the broken link check for now, we'll revisit later.