Auth\Basic: add input validation to constructor
rmccue/Requests pull request #574
Opened 2021-10-11 16:07 UTC by jrfnl

The `Basic::__construct()` method expects to receive an array of exactly two element and did validate the input received, but only threw an exception when the passed parameter did not match the expected element count, not when the passed parameter wasn't an array.

At the same time, the default value of `$args` is `null`, not an empty array and the `$user` and `$pass` properties are both public.

The only reason I can think of to have these properties `public` and the default value set to `null`, is to allow for delayed setting of the `$user` and `$pass`, after the class has already been instantiated.

To maintain the existing behaviour, but still add input validation, an exception is now thrown when the `$args` parameter is neither an array, nor `null`.

Includes;
* A dedicated test for the input validation.
* An additional test with Basic authentication with an instantiated class, but with delayed setting of the `$user` and `$pass` directly on the instantiated object. This test is solely added to document that this is a supported feature (and to safeguard against regressions in that respect).

2021-10-29 13:03 UTC, schlessera requested changes

2021-10-29 13:03 UTC, schlessera commented on src/Auth/Basic.php
> +	 * @throws \WpOrg\Requests\Exception                 On incorrect number of arguments (`authbasicbadargs`).
Should we immediately change this Exception into one that is more precise? I think it should be based on https://www.php.net/manual/en/class.badmethodcallexception.php. If we make sure that it extends `\WpOrg\Requests\Exception`, it shouldn't be a breaking change.

2021-10-29 13:24 UTC, jrfnl commented on src/Auth/Basic.php
> +	 * @throws \WpOrg\Requests\Exception                 On incorrect number of arguments (`authbasicbadargs`).
Good idea. What about making it an `ArgumentCountException` though ? Kind of feels more appropriate ?
https://www.php.net/manual/en/class.argumentcounterror.php

2021-10-29 13:28 UTC, schlessera commented on src/Auth/Basic.php
> +	 * @throws \WpOrg\Requests\Exception                 On incorrect number of arguments (`authbasicbadargs`).
That doesn't exist for PHP 5.6, though...

2021-10-30 13:51 UTC, jrfnl commented on src/Auth/Basic.php
> +	 * @throws \WpOrg\Requests\Exception                 On incorrect number of arguments (`authbasicbadargs`).
> That doesn't exist for PHP 5.6, though.

True, but that shouldn't really matter if we extend the `\WpOrg\Requests\Exception` class anyhow.

> If we make sure that it extends `\WpOrg\Requests\Exception`, it shouldn't be a breaking change.

2021-11-01 02:32 UTC, jrfnl commented on src/Auth/Basic.php
> +	 * @throws \WpOrg\Requests\Exception                 On incorrect number of arguments (`authbasicbadargs`).
I've added the `ArgumentCount` exception class + implemented use of it in this class + one other location in the code base where it seemed appropriate.

2021-11-05 09:17 UTC, schlessera approved these changes

2021-11-05 09:17 UTC, merged