Docs: full review of Hook documentation
rmccue/Requests pull request #646
Opened 2021-11-25 14:02 UTC by jrfnl

Inspired by issue #220, I've:
* Verified that all hooks listed in the documentation still exist in the codebase.
* Verified the parameters for all hooks listed in the docs with the actual parameters in the hook calls in the codebase.
* Verified that all hooks in the codebase are listed in the Hooks documentation page, with the exception of the `transport.internal....` hooks.

Note:
* The hook descriptions for the added hooks can probably use further improvement. I wasn't always sure how best to describe the hook event.
* The ordering of this list looks to be a loose "requests hooks, curl hooks, fsockopen hooks and those in the order they are called" order.
    With some of the additional hooks, it wasn't always clear where to place them within this loose order, so suggestions to improve the order are welcome.

Also note the the naming of the `request.progress` hook seems inconsistent. I do understand why the hook uses `request` instead of `requests`, but this may be something to revisit at a later point in time.

2021-11-25 21:59 UTC, jrfnl commented
Also related to #321

2021-12-07 10:06 UTC, schlessera approved these changes

2021-12-07 10:13 UTC, schlessera commented
Hmm, still on the fence about this one, as I'm not yet sure whether the documentation for the optional `$info` args is sufficient here. It might be more robust to go with @johnbillion's suggestion and provide an `$info` array in all cases, with an empty one being used for non-blocking requests. I'll think about this some more...

2021-12-08 12:41 UTC, jrfnl commented
> Hmm, still on the fence about this one, as I'm not yet sure whether the documentation for the optional `$info` args is sufficient here. It might be more robust to go with @johnbillion's suggestion and provide an `$info` array in all cases, with an empty one being used for non-blocking requests. I'll think about this some more...

Those are two separate issues to address though. The documentation is issue 1, at least with this PR it would be "hook complete", which is much better then it is now.

Deciding whether or not to always pass `$info` is a different issue and if/when it is so decided, the documentation can be further updated to reflect that change.

Generally speaking I'm in favour of John's suggestion and would recommend for hooks to have the same number of arguments every time they are called, however, making this change now _could_ be considered a breaking change as functions which "hook in" very likely will need updating (callbacks may have a different default value set - `null` - for the optional parameter from the empty array we would pass, callbacks may use `isset()` on result of `function_get_args()` for this parameter, which would break, etc).

2022-02-07 16:16 UTC, schlessera requested changes

2022-02-07 16:16 UTC, schlessera commented on docs/hooks.md
```suggestion

This optional parameter will be present when a blocking request was made (`$options['blocking' = true`) and will not be present when a non-blocking request was made (`$options['blocking' = false`). The callback signature needs to be adapted accordingly.

```

2022-02-07 16:16 UTC, schlessera commented on docs/hooks.md
```suggestion

This optional parameter will be present when a blocking request was made (`$options['blocking' = true`) and will not be present when a non-blocking request was made (`$options['blocking' = false`). The callback signature needs to be adapted accordingly.

```

2022-02-07 16:20 UTC, schlessera approved these changes

2022-02-07 16:38 UTC, merged