SslTest: split up test class
rmccue/Requests pull request #727
Opened 2022-04-25 12:30 UTC by jrfnl

### SslTest: split verify_reference_name() specific tests to dedicated test class

### Tests: introduce an SslTestCase class

... containing various methods which are used by tests for multiple different methods.

### SslTest: split match_domain() specific tests to dedicated test class

### SslTest: rename to VerifyCertificateTest

... as the remaining tests relate directly to the `verify_certificate()` method.

Including re-ordering the methods in the class to follow the order of the code in the method under test.

Related to #648

2022-05-09 15:46 UTC, schlessera requested changes

2022-05-09 15:46 UTC, schlessera commented on tests/Ssl/SslTestCase.php
> +			// If SAN is set to true, default it to the dNSName
```suggestion
			// If SAN is set to true, default it to the dNSName.
```

2022-05-09 15:46 UTC, schlessera commented on tests/Ssl/SslTestCase.php
> +			// Check that we need at least 3 components
```suggestion
			// Check that we need at least 3 components.
```

2022-05-09 15:46 UTC, schlessera commented on tests/Ssl/SslTestCase.php
> +			// Check that double wildcards don't work
```suggestion
			// Check that double wildcards don't work.
```

2022-05-09 15:46 UTC, schlessera commented on tests/Ssl/SslTestCase.php
> +			// Check that we only match with the correct number of components
```suggestion
			// Check that we only match with the correct number of components.
```

2022-05-09 15:46 UTC, schlessera commented on tests/Ssl/SslTestCase.php
> +			// Check that the wildcard only works as the full first component
```suggestion
			// Check that the wildcard only works as the full first component.
```

2022-05-09 15:46 UTC, schlessera commented on tests/Ssl/SslTestCase.php
> +			// Check that wildcards are not allowed for IPs
```suggestion
			// Check that wildcards are not allowed for IPs.
```

2022-05-09 15:46 UTC, schlessera commented on tests/Ssl/SslTestCase.php
> +			'IP address; wildcard in refence (start)' => [
```suggestion
			'IP address; wildcard in reference (start)' => [
```

2022-05-09 15:46 UTC, schlessera commented on tests/Ssl/SslTestCase.php
> +			'IP address; wildcard in refence (end)' => [
```suggestion
			'IP address; wildcard in reference (end)' => [
```

2022-05-09 16:32 UTC, jrfnl commented
@schlessera Happy to address these things, but they are all outside the scope of this PR, which just splits the test class up into method based classes, without making any other changes....

2022-05-10 09:00 UTC, schlessera approved these changes

2022-05-10 09:00 UTC, merged