New `InputValidator::is_valid_rfc2616_token()` method
rmccue/Requests pull request #849
Opened 2023-12-11 15:04 UTC by jrfnl

## Pull Request Type

This is a:
- [ ] Bug fix
- [x] New feature
- [ ] Documentation improvement
- [ ] Code quality improvement

## Context

The new method is intended to be used as a helper to allow for making solving #845 / #847 more straight-forward.

## Detailed Description

This new method validates that an arbitrary input parameter can be considered valid for use as a "token" as per the RFC 2616 specification.

Includes tests.

Ref: https://datatracker.ietf.org/doc/html/rfc2616#section-2.2

2024-01-08 11:18 UTC, schlessera requested changes

2024-01-08 11:18 UTC, schlessera commented on src/Utility/InputValidator.php
> +	 * The short version is: 1 or more ascii characters, CTRL chars and separators not allowed.
I'd capitalize the ASCII acronym, it is not an actual word.
```suggestion
	 * The short version is: 1 or more ASCII characters, CTRL chars and separators not allowed.
```

2024-01-08 11:18 UTC, schlessera commented on src/Utility/InputValidator.php
> +		return (preg_match('@^[0-9A-Za-z!#$%&\'*+.^_`|~-]+$@', $input) === 1);
These outer parentheses are superfluous here. Was that a conscious decision for clarity?
For me, this is tripping me up here in terms of readability as I initially tried to figure out what I was missing...

2024-01-08 17:42 UTC, schlessera commented
@jrfnl I've made the changes we've discussed in the call. Do you want to take a final look?

2024-01-08 17:42 UTC, schlessera approved these changes

2024-01-09 12:34 UTC, jrfnl commented on src/Utility/InputValidator.php
> +		return (preg_match('@^[0-9A-Za-z!#$%&\'*+.^_`|~-]+$@', $input) === 1);
As discussed off-GH: Yes, conscious in the sense of force of habit, as I've seen issues with operator precedence too often.

Not an issue here, so I'm fine with removing them.

2024-01-09 12:36 UTC, jrfnl commented
@schlessera Thanks for working on this together. all looks good to me.

2024-01-09 13:34 UTC, jrfnl commented
@schlessera Shall I clean up the branch before merge ? Or will you squash merge ?

2024-02-12 10:11 UTC, merged